# Generated by Django 5.2.12 on 2026-04-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixalbania', '0002_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
